CREATE DATABASE vendas_sucos;

USE vendas_sucos;

CREATE TABLE PRODUTOS
(CODIGO VARCHAR(10) NOT NULL,
 DESCRITOR VARCHAR(100) NULL,
 SABOR VARCHAR(50) NULL,
 TAMANHO VARCHAR(50) NULL,
 EMBALAGEM VARCHAR(50) NULL,
 PRECO_LISTA FLOAT NULL,
 PRIMARY KEY (CODIGO));

CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(100) NULL,
COMISSAO FLOAT NULL,
DATA_ADMISSAO DATE NULL,
FERIAS BIT(1) NULL,
PRIMARY KEY (MATRICULA)); 

CREATE TABLE itens_notas (
  NUMERO VARCHAR(5) NOT NULL,
  CODIGO VARCHAR(10) NOT NULL,
  QUANTIDADE INT(11) NULL,
  PRECO FLOAT NULL,
  PRIMARY KEY (NUMERO, CODIGO)
);

DROP TABLE itens_notas;

ALTER TABLE vendas ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES clientes (CPF);

ALTER TABLE vendas ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES vendedores (MATRICULA);

/*Crie, por linha de comando, a chave estrangeira ligando a tabela 
de PRODUTOS com a tabela de ITENS_NOTAS através do campo CODIGO e outra ligação entre a tabela NOTAS e ITENS_NOTAS através do campo NUMERO.*/
ALTER TABLE itens_notas ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES produtos (CODIGO);

ALTER TABLE itens_notas ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) REFERENCES notas (NUMERO);