DECLARE @NUMNOTAS INT
DECLARE @DATA DATE

SET @DATA = '20170101'

SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS]
WHERE DATA = @DATA

IF @NUMNOTAS > 70
	PRINT 'Muita nota'
ELSE
	PRINT 'Pouca nota'

PRINT @NUMNOTAS