DECLARE @CLIENTE VARCHAR(10)
DECLARE @IDADE INT
DECLARE @DATANASCIMENTO DATE
DECLARE @CUSTO FLOAT

SET @CLIENTE = 'João'
SET @IDADE = 10
SET @DATANASCIMENTO = '20070110'
SET @CUSTO = 10.23

PRINT @CLIENTE
PRINT @IDADE
PRINT @DATANASCIMENTO
PRINT @CUSTO

DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
WHERE DATA = '20170101'
PRINT @NUMNOTAS
