--Reescreva este script usando a função NumeroNotas no momento de inserir dados na tabela. 
-- Execute o SELECT para exibir os dados.

IF OBJECT_ID('TABELANOTAS','U') IS NOT NULL
DROP TABLE TABELANOTAS
DECLARE @TABELANOTAS TABLE (DATA DATE, NUMNOTAS INT)
DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
   INSERT INTO @TABELANOTAS (DATA, NUMNOTAS) 
    VALUES (@DATAINICIAL, [dbo].[NumeroNotas](@DATAINICIAL))
   SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END
SELECT * FROM @TABELANOTAS