
SELECT SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS]
WHERE NUMERO = 100

CREATE FUNCTION NumeroNotas (@DATA AS DATE) RETURNS INT
AS
BEGIN
	DECLARE @NUMNOTAS INT
	SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
		WHERE DATA = '20170101'
	RETURN @NUMNOTAS
END


SELECT NUMERO, [dbo].[FaturamentoNota](NUMERO) AS FATURAMENTO 
FROM [NOTAS FISCAIS]


