--Continue evoluindo o script da resposta do exercício anterior. 
--Agora, inclua o dia e o número de notas em uma tabela.

IF OBJECT_ID('TABELANOTAS', 'U') IS NOT NULL
	DROP TABLE [TABELANOTAS]

CREATE TABLE [TABELANOTAS] ([DATA] DATE, [QTDE] INT)

DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'

SET NOCOUNT ON
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL
    PRINT CONVERT(VARCHAR(10), @DATAINICIAL) + ' --> ' 
        + CONVERT(VARCHAR(10), @NUMNOTAS)
	INSERT INTO [TABELANOTAS] ([DATA], QTDE) 
	VALUES (CONVERT(VARCHAR(10), @DATAINICIAL), @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END

SELECT * FROM [TABELANOTAS]