
DECLARE @NOME VARCHAR(200)
DECLARE @ENDERECO VARCHAR(MAX)
DECLARE CURSOR1 CURSOR FOR 
SELECT NOME, ([ENDERECO 1] + ' - ' + BAIRRO + ' - ' + CIDADE + ' - ' + ESTADO + ' - ' + CEP) ENDCOMPLETO 
FROM [TABELA DE CLIENTES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME, @ENDERECO
WHILE @@FETCH_STATUS = 0
BEGIN
  PRINT @NOME + ' Endereço: ' + @ENDERECO
  FETCH NEXT FROM CURSOR1 INTO @NOME, @ENDERECO
END
CLOSE CURSOR1
DEALLOCATE CURSOR1

-- Crie um script usando um cursor para achar o valor total do faturamento para um mês e um ano.

-- Declare três variáveis: uma que recebe a quantidade, outra o preço e uma terceira que irá acumular o faturamento;
DECLARE @QUANTIDADE INT
DECLARE @PRECO FLOAT
DECLARE @ACUMULADO FLOAT
DECLARE @MES INT
DECLARE @ANO INT

SET @ACUMULADO = 0
SET @MES = 1
SET @ANO = 2017

DECLARE CURSOR1 CURSOR FOR 
	SELECT INF.QUANTIDADE AS QUANTIDADE, INF.PREÇO AS PRECO
		FROM [ITENS NOTAS FISCAIS] INF
		INNER JOIN [NOTAS FISCAIS] NF ON NF.NUMERO = INF.NUMERO
		WHERE MONTH(NF.DATA) = @MES AND YEAR(NF.DATA) = @ANO

-- Faça um loop no cursor e vá somando o faturamento de cada nota;
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @QUANTIDADE, @PRECO
WHILE @@FETCH_STATUS = 0
BEGIN
  SET @ACUMULADO = @ACUMULADO + @QUANTIDADE*@PRECO
  FETCH NEXT FROM CURSOR1 INTO @QUANTIDADE, @PRECO
END
CLOSE CURSOR1
DEALLOCATE CURSOR1
PRINT @ACUMULADO