CREATE DATABASE SUCOS_VENDAS_01;


CREATE DATABASE SUCOS_VENDAS_02
ON (NAME=SUCOS_VENDAS_DAT, FILENAME='C:\TEMP\DATA\SALES_VENDAS_02.MDF', SIZE=10, MAXSIZE=50,
	FILEGROWTH=5)
LOG ON (NAME=SUCOS_VENDAS_LOG FILENAME='C:\TEMP\DATA\SALES_VENDAS_02.LDF', SIZE=10, MAXSIZE=50,
	FILEGROWTH=5);

--DROP DATABASE SUCOS_VENDAS_01;

use [SUCOS_VENDAS];

CREATE TABLE [TABELA DE CLIENTES](
    [CPF] [VARCHAR] (11) ,
    [NOME] [VARCHAR] (100) ,
    [ENDERECO 1] [VARCHAR] (150) ,
    [ENDERECO 2] [VARCHAR] (150) ,
    [BAIRRO] [VARCHAR] (50) ,
    [CIDADE] [VARCHAR] (50) ,
    [ESTADO] [VARCHAR] (2) ,
    [CEP] [VARCHAR] (8) ,
    [DATA DE NASCIMENTO] [DATE],
    [IDADE] [SMALLINT],
    [SEXO] [VARCHAR] (1) ,
    [LIMITE DE CREDITO] [MONEY] ,
    [VOLUME DE COMPRA] [FLOAT] ,
    [PRIMEIRA COMPRA] [BIT]
);